---
new_page_extension: md
auto_deploy: false
admin_path: public
webhook_url: 
sections:
- type: heading
  label: Menu
- type: heading
  label: General Config
- type: document
  path: src/data/general/menu.json
  label: Menu Links
- type: document
  path: src/data/general/footer.json
  label: Footer Links
- type: heading
  label: Front Page (Home)
- type: directory
  path: src/data/homepages
  label: Home
  create: none
  match: home.json
- type: directory
  path: src/data/homepages
  label: Welcome Section
  create: none
  match: welcome-section.json
- type: heading
  label: Pages
- type: directory
  path: src/data/inner-pages
  label: About Us Page
  create: none
  match: about-us-page.json
- type: directory
  path: src/data/inner-pages
  label: Contact Page
  create: none
  match: contact-us-page.json
- type: directory
  path: src/data/inner-pages
  label: FAQ's
  create: documents
  match: faq.json
- type: heading
  label: Content
- type: directory
  path: src/data/blog-post
  label: Event Post
  create: documents
  match: "**/*"
- type: directory
  path: src/data/products
  label: Products
  create: documents
  match: "**/*"
- type: directory
  path: src/data/testimonials
  label: Testimonials
  create: documents
  match: "**/*"
upload_dir: src/data/images
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
