---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: General Config
- type: document
  path: src/data/general/menu.json
  label: Menu Links
- type: directory
  path: src/data/general
  label: Footer Links
  create: none
  match: footer.json
- type: heading
  label: Front Page (Home)
- type: heading
  label: Pages
- type: heading
  label: Content
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
